### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [NasirNobin/zsh-valet#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by NasirNobin** [comment]
[License](https://github.com/NasirNobin/zsh-valet/blob/main/LICENSE) added. 

Appreciate you adding it under `awesome-zsh-plugins plgins`. Thanks a lot.
